name       : libsecret
version    : 0.18.5
release    : 11
source     :
    - http://ftp.gnome.org/pub/gnome/sources/libsecret/0.18/libsecret-0.18.5.tar.xz : 9ce7bd8dd5831f2786c935d82638ac428fa085057cc6780aba0e39375887ccb3
homepage   : https://live.gnome.org/Libsecret
license    :
    - LGPL-2.1
summary    : The libsecret package contains a GObject based library for accessing the Secret Service API.
builddeps  :
    - libgcrypt-devel
    - vala
component  : desktop.gnome.core
description: |
    The libsecret package contains a GObject based library for accessing the Secret Service API.
setup      : |
    %configure --disable-static \
               --disable-manpages
build      : |
    %make
install    : |
    %make_install
