name       : libsecret
version    : 0.19.1
release    : 13
source     :
    - https://download.gnome.org/sources/libsecret/0.19/libsecret-0.19.1.tar.xz : 8583e10179456ae2c83075d95455f156dc08db6278b32bf4bd61819335a30e3a
component  : desktop.gnome.core
license    : LGPL-2.1-or-later
summary    : The libsecret package contains a GObject based library for accessing the Secret Service API.
description: |
    The libsecret package contains a GObject based library for accessing the Secret Service API.
builddeps  :
    - libgcrypt-devel
    - vala
setup      : |
    %configure --disable-static --disable-manpages
build      : |
    %make
install    : |
    %make_install
