name       : libsecret
version    : 0.20.1
release    : 14
source     :
    - https://download.gnome.org/sources/libsecret/0.20/libsecret-0.20.1.tar.xz : 57f73e94ec6263a17a077fb809cf8cf424637a897a7f15b4eec42ce4aef52447
component  : desktop.gnome.core
license    : LGPL-2.1-or-later
summary    : The libsecret package contains a GObject based library for accessing the Secret Service API.
description: |
    The libsecret package contains a GObject based library for accessing the Secret Service API.
builddeps  :
    - libgcrypt-devel
    - vala
setup      : |
    %configure --disable-static --disable-manpages
build      : |
    %make
install    : |
    %make_install
