name       : libsecret
version    : 0.18.8
release    : 12
source     :
    - https://download.gnome.org/sources/libsecret/0.18/libsecret-0.18.8.tar.xz : 3bfa889d260e0dbabcf5b9967f2aae12edcd2ddc9adc365de7a5cc840c311d15
component  : desktop.gnome.core
license    : LGPL-2.1-or-later
summary    : The libsecret package contains a GObject based library for accessing the Secret Service API.
description: |
    The libsecret package contains a GObject based library for accessing the Secret Service API.
builddeps  :
    - libgcrypt-devel
    - vala
setup      : |
    %configure --disable-static --disable-manpages
build      : |
    %make
install    : |
    %make_install
