name       : libsecret
version    : 0.20.5
release    : 20
source     :
    - https://download.gnome.org/sources/libsecret/0.20/libsecret-0.20.5.tar.xz : 3fb3ce340fcd7db54d87c893e69bfc2b1f6e4d4b279065ffe66dac9f0fd12b4d
component  : desktop.gnome.core
license    : LGPL-2.1-or-later
summary    : The libsecret package contains a GObject based library for accessing the Secret Service API.
description: |
    The libsecret package contains a GObject based library for accessing the Secret Service API.
builddeps  :
    - libgcrypt-devel
    - vala
setup      : |
    %meson_configure -Dmanpage=false -Dgtk_doc=false
build      : |
    %ninja_build
install    : |
    %ninja_install
