name       : libsecret
version    : 0.20.4
release    : 19
source     :
    - https://download.gnome.org/sources/libsecret/0.20/libsecret-0.20.4.tar.xz : 325a4c54db320c406711bf2b55e5cb5b6c29823426aa82596a907595abb39d28
component  : desktop.gnome.core
license    : LGPL-2.1-or-later
summary    : The libsecret package contains a GObject based library for accessing the Secret Service API.
description: |
    The libsecret package contains a GObject based library for accessing the Secret Service API.
builddeps  :
    - libgcrypt-devel
    - vala
setup      : |
    %configure --disable-static --disable-manpages
build      : |
    %make
install    : |
    %make_install
