name       : libsecret
version    : 0.20.2
release    : 16
source     :
    - https://download.gnome.org/sources/libsecret/0.20/libsecret-0.20.2.tar.xz : 81e9143833785cdcf96c1da5d0357a8bcf0cd2b0119f15aa0cae775d1f19ffc3
component  : desktop.gnome.core
license    : LGPL-2.1-or-later
summary    : The libsecret package contains a GObject based library for accessing the Secret Service API.
description: |
    The libsecret package contains a GObject based library for accessing the Secret Service API.
builddeps  :
    - libgcrypt-devel
    - vala
setup      : |
    %configure --disable-static --disable-manpages
build      : |
    %make
install    : |
    %make_install
